Twippera.config.setLocale_new(
    ({
        "wayd" : "What are you doing?",
        "ca"   : "Characters available",
        "set"  : "Settings",
        "un"   : "username",
        "pw"   : "password",
        "ar"   : "Auto Refresh",
        "per"  : "per",
        "min"  : "minutes",
        "to"   : "Timeout",
        "sec"  : "seconds",
        "ear"  : "Enable Auto Refresh",
        "lang" : "Languages",
        "save" : "Save",
        "abt"  : "About",
        "recent"  : "Recent",
        "replies"  : "Replies",
        "favorites" : "Favorites",
        "public": "Public",
        "cch" : "Cache",
        "msg" : "messages",
        "update": "New Version Avalilable",
        "download": "Download",
        "ok": "OK",
        "cancel": "Cancel",
        "close": "Close",
        "timeout": "Connection timeout",
        "about": "About",
        "version": "Version",
        "author": "Author",
        "design": "Design",
        "less": "less than a minute ago",
        "minago": " minute ago",
        "minsago": "minutes ago",
        "hrago": " hour ago",
        "hrsago": " hours ago"
    })
);
