// English
// en.js

Twippera.config.loadLocaleFile({
    "wayd" : "What are you doing?",
    "ca"   : "Characters available",
    "set"  : "Settings",
    "un"   : "username",
    "pw"   : "password",
    "ar"   : "Auto Refresh",
    "per"  : "per",
    "min"  : "minutes",
    "to"   : "Timeout",
    "sec"  : "seconds",
    "ear"  : "Enable Auto Refresh",
    "lang" : "Languages",
    "abt"  : "About",
    "update": "New Version Avalilable",
    "download": "Download",
    "save" : "Save",
    "ok": "OK",
    "cancel": "Cancel",
    "close": "close",
    "version": "Version",
    "author": "Author",
    "design": "Design",
    "trans": "Translation",
    "less": "less than a minute ago",
    "minago": " minute ago",
    "minsago": " minutes ago",
    "hrago": " hour ago",
    "hrsago": " hours ago",
    "dayago": " day ago",
    "daysago": " days ago",
    "timeouted": "Connection timeout",
    "recent"  : "Recent",
    "replies"  : "Replies",
    "favorites" : "Favorites",
    "cch" : "Cache",
    "msg" : "messages"
});
