// Japanese
// ja.js

Twippera.config.loadLocaleFile({
    "wayd" : "何してるの?",
    "ca"   : "残り文字数",
    "set"  : "設定",
    "un"   : "ユーザネーム",
    "pw"   : "パスワード",
    "ar"   : "自動更新",
    "per"  : "",
    "min"  : "分おき",
    "to"   : "タイムアウト",
    "sec"  : "秒",
    "ear"  : "自動更新を有効にする",
    "lang" : "言語",
    "save" : "保存",
    "abt"  : "Twippera について",
    "recent"  : "ログ",
    "replies"  : "返信",
    "favorites" : "お気に入り",
    "cch" : "キャッシュ",
    "msg" : "件",
    "update": "新しいヴァージョンがリリースされています",
    "download": "ダウンロード",
    "ok": "はい",
    "cancel": "いいえ",
    "close": "閉じる",
    "timeouted": "接続がタイムアウトしました",
    "version": "ヴァージョン",
    "author": "製作",
    "design": "デザイン",
    "trans": "翻訳",
    "less": "1 分以内",
    "minago": " 分前",
    "minsago": " 分前",
    "hrago": " 時間前",
    "hrsago": " 時間前",
    "dayago": " 日前",
    "daysago": " 日前"
});
