// Latvian
// lv.js

Twippera.config.loadLocaleFile({
    "wayd" : "Ko tu dari?",
    "ca"   : "Pieejamo simbolu skaits",
    "set"  : "Uzstādījumi",
    "un"   : "lietotājvārds",
    "pw"   : "parole",
    "ar"   : "Auto atjaunošana",
    "per"  : "katru",
    "min"  : "minūtes",
    "to"   : "Pārtraukums",
    "sec"  : "sekundes",
    "ear"  : "Iestatīt auto atjaunošanu",
    "lang" : "Valodas",
    "save" : "Saglabāt",
    "abt"  : "Par",
    "recent"  : "Jaunākais",
    "replies"  : "Atsauces",
    "favorites" : "Favorīti",
    "cch" : "Kešatmiņa",
    "msg" : "ziņas",
    "update": "Pieejama jauna versija",
    "download": "Lejupielāde",
    "ok": "OK",
    "cancel": "Atcelt",
    "close": "Aizvērt",
    "timeouted": "Nav izveidots savienojums",
    "version": "Versija",
    "author": "Autors",
    "design": "Dizains",
    "trans": "Tulkojums",
    "less": "mazāk kā minūti iepriekš",
    "minago": " minūti iepriekš",
    "minsago": " minūtes iepriekš",
    "hrago": " stundu iepriekš",
    "hrsago": " stundas iepriekš",
    "dayago": " day ago",
    "daysago": " days ago"
});
