// Norwegian
// no.js

Twippera.config.loadLocaleFile({
    "wayd" : "Hva gjør du?",
    "ca"   : "Tegn igjen",
    "set"  : "Innstillinger",
    "un"   : "brukernavn",
    "pw"   : "passord",
    "ar"   : "Oppdatér automatisk",
    "per"  : "per",
    "min"  : "minutter",
    "to"   : "Tidsavbrudd",
    "sec"  : "sekunder",
    "ear"  : "Aktivér automatisk oppdatering",
    "lang" : "Språk",
    "save" : "Lagre",
    "abt"  : "Om",
    "update": "Ny versjon tilgjengelig",
    "download": "Last ned",
    "ok": "OK",
    "cancel": "Avbryt",
    "close": "Lukk",
    "version": "Versjon",
    "author": "Opphavsrett",
    "design": "Design",
    "trans": "Oversettelse",
    "less": "mindre enn et minutt siden",
    "minago": " minutt siden",
    "minsago": " minutter siden",
    "hrago": " time siden",
    "hrsago": " timer siden",
    "timeouted": "Forbindelse avbrutt",
    "recent"  : "Nylig",
    "replies"  : "Svar",
    "favorites" : "Favoritter",
    "cch" : "Minne",
    "msg" : "meldinger",
    "dayago": " day ago",
    "daysago": " days ago"
});
