// Simplified Chinese
// // sp_ch.js
Twippera.config.loadLocaleFile({
    "wayd" : "写点儿什么?",
    "ca"   : "剩余字数",    
    "set"  : "设置",    
    "un"   : "用户名",    
    "pw"   : "密码",    
    "ar"   : "自动刷新",    
    "per"  : "每隔",    
    "min"  : "分钟",        
    "to"   : "超时",        
    "sec"  : "秒",        
    "ear"  : "激活自动刷新",        
    "lang" : "语言",        
    "save" : "保存",        
    "abt"  : "关于",        
    "recent"  : "Recent",        
    "replies"  : "Replies",        
    "favorites" : "Favorites",        
    "cch" : "Cache",        
    "msg" : "messages",
    "update": "发现新版本",
    "download": "下载",
    "ok": "OK",
    "cancel": "取消",
    "close": "关闭",
    "timeouted": "连接超时",
    "version": "版本",
    "author": "作者",
    "design": "设计",
    "trans": "翻译",
    "less": "刚刚",
    "minago": " 分钟前",
    "minsago": "  分钟前",
    "hrago": " 小时前",
    "hrsago": " 小时前",
    "dayago": " day ago",
    "daysago": " days ago"});
